### PR TITLE
Commas in numbers

### LINKED ISSUE #147: Commas in numbers
Use the GitHub title line for your issue, then delete these lines.

Please log a separate GitHub issue for each comment.
## What do you need?

What is the problem?
## Which entry/section is this related to?

For example: Hyperlinks
## Good example

Have you seen style content elsewhere we should look at?

### PR DESCRIPTION
**Pull request by joolswood**
## Description

Change guidance on commas and numbers, to improve readability.
Correct examples.

This will close #147 

## Definition of Done

- [x] PR approved by Libby
- [ ] Related [GitHub issues](https://waffle.io/AusDTO/gov-au-content-guide) closed
- [x] Update to [Updates page](http://content-style-guide.apps.staging.digital.gov.au/updates/)

### CODE REVIEW

**Comment by joolswood** [comment]
Actually, while we are looking at this page, can we improve on this line too? `Use a word for people or animals upwards from 1 million, for example 22.3 million.`

Maybe my brain is running slow, but why are we specifying animals here? We would usually write `1 million widgets` wouldn't we so why specify only for people and animals? @libbyv

**Comment by libbyv** [comment]
Agree. It's confusing.

How about this?

Use the word 'million' instead of digits for anything above 1 million eg
22.3 million Australians

?


*DTO Content Community Lead*
*0408 283 745*
*www.DTO.gov.au <http://www.DTO.gov.au>*

**Comment by joolswood** [comment]
Do we even need the extra example? ie

```
Use the word million instead of digits for 1 million and upwards.

**For example**

> - 1 to 9, not one to nine
> - 10 to 9999
> - 10,000 to 1 million
```

**Comment by joolswood** [comment]
Hey @libbyv sorry last set of changes to look at.

**Comment by libbyv** [comment]
Good to go, thanks Jools.

**Pull request merged**
