### PR TITLE
Sb edits

### PR DESCRIPTION
**Pull request by fearlesssteven**
## Description

* Updates to the abbreviation entry
* Links to GitHub issues resolved

## Definition of Done

- [ ] Acceptance testing (for code changes - TBD)
- [ ] Draft reviewed by other Content Designer
- [ ] Update to [Updates page](http://content-style-guide.apps.staging.digital.gov.au/updates/)
- [ ] PR approved by Libby
- [ ] Related [GitHub issues](https://waffle.io/AusDTO/gov-au-content-guide) closed

### CODE REVIEW

**Comment by michaelhugill** [comment]
@fearlesssteven @joolswood Hi, are you wanting me to be the Content Designer who reviews the draft? If so, what's the easiest way for me to see/do that do you think?

**Comment by joolswood** [comment]
Hey @fearlesssteven do you mind populating the fields in the issue? I can show you how if you need.

**Comment by joolswood** [comment]
Related to #123

**Comment by joolswood** [comment]
Reminder to myself to reference this: https://groups.google.com/a/digital.gov.au/forum/#!topic/content-design-in-government/h_TKih9juYg

**Comment by joolswood** [comment]
Hey @fearlesssteven I'm going to put your changes into `bugfix/123-contractions` and close this branch ok - it's a bit neater that way.

**Pull request closed without merging**
