### PR TITLE
Bugfix/106 gerunds

### LINKED ISSUE #106: Gerund use in headings
## What do you need?

I've been having some discussions about present tense vs present continuous (gerund) for page names and sub headings. It's coming up a lot in topic (e.g ‘set up’ vs ‘setting up’ or ‘providing...’):

I know present tense is preferenced in the style guide but it only makes sense to me (as a page name or subheading) for transactional content where a user can complete a task (e.g. 'apply for a visa'). The gerund seems more appropriate for guidance.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/v.html#voice

### PR DESCRIPTION
**Pull request by joolswood**
## Description

Adds gerund subheading content and fixes some examples.
## Additional information

This will close #106 
## Definition of Done
- [ ] PR approved by Libby
- [ ] Related [GitHub issues](https://waffle.io/AusDTO/gov-au-content-guide) closed
- [ ] Update to [Updates page](http://content-style-guide.apps.staging.digital.gov.au/updates/)

### CODE REVIEW

**Comment by joolswood** [comment]
Hey @libbyv can we spend some time on this?

**Comment by libbyv** [comment]
Sure, what do you need me to do?

**Comment by joolswood** [comment]
Just slacking you a screengrab. I drafted some words based on Michelle’s start and comments from Donna. I think most of it is correct. The only bit I’m still a bit iffy on is: `Sometimes it helps to use a gerund in a subheading to signpost content that is guidance.` and onwards.

**Comment by libbyv** [comment]
A gerund is when the 'ing' form of a verb is turned into a noun. Eg the thinking behind this.

Avoid gerunds like 'submitting' or 'writing' in paragraphs and page titles.

Use direct language instead.

NO FURTHER CHANGES

**Comment by joolswood** [comment]
@michellemortimer to collect some examples for review

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/24

**Pull request closed without merging**
