### PR TITLE
fix bulletpoints

### LINKED ISSUE #180: Second level bullet points
## What do you need?

Guidance on using (or not using) second level bullet points.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/b.html#bullet-point-lists
## Good example

https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bullet-points-steps
https://pages.18f.gov/content-guide/punctuation/

### PR DESCRIPTION
**Pull request by joolswood**
## Description

Add guidance around not using second level bullets (re-write instead).

Not yet ready to merge.
## Additional information

This will close #180 
## Definition of Done
- [x] Acceptance testing (for code changes - TBD)
- [ ] Draft reviewed by other Content Designer
- [ ] Update to [Updates page](http://content-style-guide.apps.staging.digital.gov.au/updates/)
- [ ] PR approved by Libby
- [ ] Related [GitHub issues](https://waffle.io/AusDTO/gov-au-content-guide) closed

### CODE REVIEW

**Comment by joolswood** [comment]
I'm trying to come up with a good example of a multi level bullet point list to rewrite. See the example. Thoughts?
screen shot 2016-10-25 at 2 23 18 pm
screen shot 2016-10-25 at 2 23 24 pm

**Comment by joolswood** [comment]
Hey @klepas I'm struggling with the CSS embiggening bullet points from 2nd level onwards for the purposes of this example. Any chance we can fix this without having to wait for dev work on the brand new guide?

(I had to do bad hacky things like this in dev tools to generate the above screenshot
```
<style>
ul, ol, p{font-size: 17px;
    font-size: 1.1rem}
</style>
```
)

**Comment by klepas** [comment]
Fixed. (:

**Comment by joolswood** [comment]
Thanks @klepas We're getting an extra space between 2 sets of second level points, see pic

screen shot 2016-11-08 at 8 48 38 am

Can you add a fix for this too?

**Comment by klepas** [comment]
@joolswood Done. (:

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/23

**Pull request closed without merging**
