### PR TITLE
Improve guidance for complex images

### PR DESCRIPTION
**Pull request by joolswood**
Suggestion from @andrew.arch - but still need to check the wording.

### CODE REVIEW

**Comment by joolswood** [comment]
Need to add updates doco.

**Comment by AndrewArch** [comment]
"Explain why you have used the graph, chart or diagram in the content next to it"

Maybe: "Explain why you have used the graph, chart or diagram - what it shows,  demonstrates or illustrates -  in the nearby content"

and for an example, can we reference another agency?
eg http://www.apsc.gov.au/publications-and-media/current-publications/building-capability and Figure 1

**Comment by joolswood** [comment]
I've cut that down a bit:

```
Complex images such as graphs, charts and diagrams only need a short alt text but they should link to a longer description (long text) or table of data.

You should also write content near the complex image that explains why it is there and what it shows.
```

What do you think?

RE: the example I'm thinking maybe hold off until we have something simpler (preferably one we've used elsewhere in a DTO project) to use.

**Comment by AndrewArch** [comment]
looks good, but suggest ...

Complex images such as graphs, charts and diagrams only need a short alt text that will be different from their caption and briefly describes the content.

You should also write content near the complex image that explains why the image is there and what it shows or highlights. In the content it is also good practice to have a text link to a longer description of the image (imagine you're describing it during a radio interview) or to a table of the data used to generate the graph/chart.

**Comment by joolswood** [comment]
@AndrewArch Given this is getting more complex, I've just tried to set this out as a list. Can you confirm if what is called a `long text` can also include a table? I can't find guidance if you wouldn't use `longdesc` to link to a table.

```
### Complex images

Complex images such as graphs, charts and diagrams need:

- a short alt text that briefly describes the content (this should be different from the text of a caption)
- content near the image that explains why it is there and what it shows or highlights
- a text link with the `longdesc` attribute that links to a page with the long text alternative.

Long text alternative is a full description of a complex image or a table of data used to generate the graph or chart.

To write long text imagine you're describing the complex image in a radio interview.
```

**Comment by joolswood** [comment]
Thanks @AndrewArch [made that change](https://github.com/AusDTO/gov-au-content-guide/pull/161/commits/14e82d7dcd49b2cdeaa8cdaf2d8f875f6fd3275b).

Now I'm wondering about this text. Aren't we covering off `informative images` now with the `complex images` content?

```
Informative images
Informative images should have a short description conveying the essential information presented by the image.
```

**Comment by AndrewArch** [comment]
Maybe `To write long text imagine you're describing the essential elements of a complex image in a radio interview.` instead of `To write long text imagine you're describing the complex image in a radio interview.`

**Comment by AndrewArch** [comment]
re `informative images` - I'd leave that (photos and other image types can be informative),  but add a cross reference to `complex images such as graphs`

**Comment by joolswood** [comment]
Hey @AndrewArch do you want to do another read through? Or happy to progress?

**Comment by AndrewArch** [comment]
The changes proposed in https://github.com/AusDTO/gov-au-content-guide/pull/161/files look good to me - I recommend accepting them.

**Comment by joolswood** [comment]
Thanks @AndrewArch merging.

**Pull request merged**
